apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: tidb-failure
  namespace: blade
spec:
  action: pod-failure
  mode: one
  duration: "10m"
  selector:
    namespaces:
      - blade
    labelSelectors:
      "app.kubernetes.io/instance": "jptest"
      "app.kubernetes.io/component": "tidb"
  scheduler:
    cron: "@every 10m"

