apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: tikv-failure
  namespace: blade
spec:
  action: pod-failure
  mode: one
  duration: "40m"
  selector:
    namespaces:
      - blade
    labelSelectors:
      "app.kubernetes.io/instance": "jptest"
      "app.kubernetes.io/component": "tikv"
  scheduler:
    cron: "@every 50m"

